---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: src/menus/navigation.json
  label: Menu Links
- type: directory
  path: src/cms/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - page
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run forestry:preview
